### PR TITLE
`Req.Request`, `Req.Response`: Change headers to be maps

### LINKED ISSUE #223: Change headers to maps
Currently Req request and response headers are lists of tuples, e.g.: `[{"foo", "bar"}]`. This is a standard across the ecosystem (with minor difference that some Erlang libraries use charlists instead of binaries.) This particular representation makes sense because the same header might appear multiple times, see [RFC 9110 § 5.2](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.2).

There are some problems with this particular choice though:

1. We cannot use `headers[key]`
2. We cannot use pattern matching

In short, this representation isn't very ergonomic to use.

## 1. Headers as Maps

Both of these problems can be solved by switching the representation to maps of string keys and list values:

```diff
- [{"foo", "bar"}]
+ %{"foo" => ["bar"]}
```

This is similar to [Go's net/http `Header` type](https://pkg.go.dev/net/http#Header).

Let's see some example rewrites:

```diff
- [value] = Req.Response.get_header(response, "content-type")
+ [value] = response.headers["content-type"]
```

or in certain situations even better:

```elixir
case response do
  %{headers: %{"content-type" => ["application/json" <> _]}} ->
end
```

## Option 2: Headers as Structs

An interesting idea is to go further and have a struct:

```elixir
defmodule Req.Headers do
  defstruct [:map]
end

resp = Req.get!("https://elixir-lang.org")
resp.headers["content-type"] #=> ["text/html"]
resp.headers["Content-Type"] #=> ["text/html"] (RFC says they need to be treated case-insensitively!)
```

and we _still_ could pattern match:

```elixir
case response do
  %{headers: %{map: %{"content-type" => "text/html" <> _}}} ->
end
```

however here we cannot treat the names case insensitively so it's probably better to continue assuming they are lowercase (and enforce it: #196).

The struct gives us opportunity for slightly different Access implementation however:

```diff
- resp.headers["content-type"] #=> ["text/html"]
+ resp.headers["content-type"] #=> "text/html"
```

and the semantics would be similar to [Go's `Header.Get()`](https://pkg.go.dev/net/http#Header.Get):

> Get gets the first value associated with the given key. 

and then we'd have something like [`Header.Values()`](https://pkg.go.dev/net/http#Header.Values).

With structs we can implement protocols. For example, we may want to have an enumerable implementation for interop:

```elixir
Enum.to_list(resp.headers) #=> [{"content-type", "text/html"}, ...]
```

And perhaps Collectable too:

```elixir
Enum.into([{"content-type", "text/html"}], resp.headers)
```

Basically, we have extensibility.

All that being said, while I thing these are nice things, I feel like structs are a more complicated solution than plain maps and I'm not sure they give us significant benefits at the moment.

### PR DESCRIPTION
**Pull request by wojtekmach**
Closes #223

### CODE REVIEW

**Comment by florish** [comment]
Hi @wojtekmach, thanks for all the work put into `Req`!

We're in the processing of migrating from 0.3 to 0.4, and in the process I assumed that the `:headers` option in `Req.new/1` and `Req.update/2` would also have been changed to expect map data instead of lists. E.g.:

```
req = Req.new(url: "https://example.com", headers: %{"accept" => ["application/json"]})
Req.update(req, headers: %{"foo" => ["bar"]})
```

Is there a specific reason that in both cases, the `:headers` values are still lists in 0.4.x?

**Comment by wojtekmach** [comment]
Both are supported! (If maps are not, it’s a bug.) the idea is passing eg `accept: “application/json”` is much more concise than the equivalent map with, notably, list of values.

**Comment by wojtekmach** [comment]
In hindsight this is not necessarily super obvious so a PR that updates docs is welcome as always!

**Comment by florish** [comment]
@wojtekmach See #241 for PR, feel free to change anything you like!

**Pull request merged**
