### PR TITLE
Update Finch to 0.9.1

### PR DESCRIPTION
**Pull request by QuinnWilton**
Hey Wojtek!

We're relying on the latest version of `Finch`, so I just wanted to bump the version in `Req` so that we could remove an `override: true` in our `mix.exs`. Everything should be backwards compatible, and I think `Req` actually already relied on `~> 0.9.0` because that's when support for Unix sockets was added.

### CODE REVIEW

**Comment by wojtekmach** [comment]
Thx, Ill cut a release tomorrow

**Comment by QuinnWilton** [comment]
Thank you!

**Comment by coop** [comment]
Thanks @QuinnWilton - I was just about to open a PR. @wojtekmach any chance you'd be able to cut a release? :)

**Comment by wojtekmach** [comment]
v0.2.1 is out, sorry for the hold up!

**Comment by coop** [comment]
Thank you so much @wojtekmach - also thanks for the lib, it's cut down on the boilerplate I used to write.

**Pull request merged**
